// <auto-generated />
using System;
using Backend.Data;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "activity_verdict", "activity_verdict", new[] { "work", "rest", "unknown" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "report_status_color", "report_status_color", new[] { "green", "yellow", "red" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_status", "session_status", new[] { "active", "paused", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "employee", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.ActivityRecord", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_name");

                    b.Property<ActivitySourceType>("SourceType")
                        .HasColumnType("activity_source_type")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<ActivityVerdict>("Verdict")
                        .HasColumnType("activity_verdict.activity_verdict")
                        .HasColumnName("verdict");

                    b.HasKey("ActivityId");

                    b.HasIndex("Domain");

                    b.HasIndex("SessionId");

                    b.HasIndex("Verdict");

                    b.ToTable("activity_records", (string)null);
                });
                });

            modelBuilder.Entity("Backend.Models.DailyReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<decimal>("RestPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rest_percent");

                    b.Property<ReportStatusColor>("StatusColor")
                        .HasColumnType("report_status_color.report_status_color")
                        .HasColumnName("status_color");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WorkPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("work_percent");

                    b.HasKey("ReportId");

                    b.HasIndex("ReportDate")
                        .HasDatabaseName("idx_daily_reports_report_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_daily_reports_user_id");

                    b.HasIndex("UserId", "ReportDate")
                        .IsUnique();

                    b.ToTable("daily_reports", (string)null);
                });
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TechStackItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ItemId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tech_stack_items_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tech_stack_user_name");

                    b.HasIndex("UserId", "Position")
                        .IsUnique();

                    b.ToTable("tech_stack_items", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role.user_role")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Violation", b =>
                {
                    b.Property<Guid>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("violation_id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disputed");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ScreenshotPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("screenshot_path");

                    b.HasKey("ViolationId");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_violations_created_at");

                    b.ToTable("violations", (string)null);
                });

            modelBuilder.Entity("Backend.Models.WorkSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("RestTimeSec")
                        .HasColumnType("integer")
                        .HasColumnName("rest_time");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<SessionStatus>("Status")
                        .HasColumnType("session_status.session_status")
                        .HasColumnName("status");

                    b.Property<int>("TotalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("total_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.Property<int>("WorkTimeSec")
                        .HasColumnType("integer")
                        .HasColumnName("work_time");

                    b.HasKey("SessionId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "WorkDate");

                    b.ToTable("work_sessions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ActivityRecord", b =>
                {
                    b.HasOne("Backend.Models.WorkSession", "Session")
                        .WithMany("ActivityRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Backend.Models.DailyReport", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("DailyReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.TechStackItem", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("TechStackItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.OwnsOne("Backend.Models.UserSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("theme");

                            b1.Property<TimeSpan>("WorkTime")
                                .HasColumnType("interval")
                                .HasColumnName("work_time");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.ToJson("settings");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Violation", b =>
                {
                    b.HasOne("Backend.Models.ActivityRecord", "Activity")
                        .WithOne("Violation")
                        .HasForeignKey("Backend.Models.Violation", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Backend.Models.WorkSession", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("WorkSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.ActivityRecord", b =>
                {
                    b.Navigation("Violation");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("DailyReports");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TechStackItems");

                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("Backend.Models.WorkSession", b =>
                {
                    b.Navigation("ActivityRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
